import {generateAPIExportGlueCode} from "@anio-software/enkore.target-js-factory"
import {getTargetIntegrationAPIMethodNames} from "@anio-software/enkore.target-js-factory/targetIntegration"
import {getProjectAPIMethodNames} from "@anio-software/enkore.target-js-factory/project"
import {getAutogenerateAPIMethodNames} from "@anio-software/enkore.target-js-factory/autogenerate"

import {
	createConfig,
	createTargetJSNoneOptions,
	createAutogeneratedFile
} from "@asint/enkore/spec/factory"

const isPublicRelease = (
	process.env?.RELEASE_VERSION ?? ""
).startsWith("vp")

export const config: unknown = createConfig({
	target: {
		name: "js-none",
		options: createTargetJSNoneOptions({
			exports: {
				"targetIntegrationAPI": {
					checkAgainstInterface: [
						"@anio-software/enkore.spec",
						"EnkoreTargetIntegrationAPI_V0_Rev0"
					]
				}
			},

			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@asint": {
					registry: "anioSoftware"
				},
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				packageName: "@asint/enkore-target__js-none",
				registry: "anioSoftware"
			}, {
				packageName: "@anio-software/enkore.target-js-none",
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: [
		createAutogeneratedFile({
			destinationPath: `project/export/targetIntegrationAPI/__aggregatedExports.mts`,
			generator() {
				let code = ``

				code += `import {generateTargetIntegrationAPI} from "@anio-software/enkore.target-js-factory/targetIntegration"\n`
				code += `import type {EnkoreTargetIntegrationAPI_V0_Rev0 as API} from "@anio-software/enkore.spec"\n`

				code += `const api = await generateTargetIntegrationAPI("js-none");\n`

				code += generateAPIExportGlueCode(
					"API", "api", getTargetIntegrationAPIMethodNames()
				)

				return code
			}
		}),

		createAutogeneratedFile({
			destinationPath: `project/export/project/__aggregatedExports.mts`,
			generator() {
				let code = ``

				code += `import {generateProjectAPI} from "@anio-software/enkore.target-js-factory/project"\n`
				code += `import type {EnkoreTargetJSProjectAPI_V0_Rev0 as API} from "@anio-software/enkore.spec"\n`

				code += `const api = await generateProjectAPI(["inferFromCLIArgs"]);\n`

				code += generateAPIExportGlueCode(
					"API", "api", getProjectAPIMethodNames()
				)

				return code
			}
		}),

		createAutogeneratedFile({
			destinationPath: `project/export/autogenerate/__aggregatedExports.mts`,
			generator() {
				let code = ``

				code += `import {generateAutogenerateAPI} from "@anio-software/enkore.target-js-factory/autogenerate"\n`
				code += `import type {EnkoreTargetJSAutogenerateAPI_V0_Rev0 as API} from "@anio-software/enkore.spec"\n`

				code += `const api = await generateAutogenerateAPI("js-none");\n`

				code += generateAPIExportGlueCode(
					"API", "api", getAutogenerateAPIMethodNames()
				)

				return code
			}
		})
	]
})
