import {generateAPIExportGlueCode} from "@enkore/target-js-factory"
import {getTargetIntegrationAPIMethodNames} from "@enkore/target-js-factory/targetIntegration"
import {defineConfig, defineAutogeneratedFile} from "enkore"
import {defineTargetConfig} from "@enkore-target/js-none"

export default defineConfig({
	target: defineTargetConfig({
		exports: {
			"targetIntegrationAPI": {
				checkAgainstInterface: [
					"@enkore/spec",
					"EnkoreTargetIntegrationAPI_V0_Rev0"
				]
			}
		}
	}),

	autogeneratedFiles: [
		defineAutogeneratedFile(
			`project/export/targetIntegrationAPI/__aggregatedExports.mts`,
			() => {
				let code = ``

				code += `import {generateTargetIntegrationAPI} from "@enkore/target-js-factory/targetIntegration"\n`
				code += `import type {EnkoreTargetIntegrationAPI_V0_Rev0 as API} from "@enkore/spec"\n`

				code += `const api = await generateTargetIntegrationAPI({target: "js-none"});\n`

				code += generateAPIExportGlueCode(
					"API", "api", getTargetIntegrationAPIMethodNames()
				)

				return code
			}
		)
	]
})
